name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start Minikube
      uses: medyagh/setup-minikube@master
    - name: Verify Cluster
      run: kubectl get nodes
    - name: Build Docker Image Inside Minikube
      run: |
          eval $(minikube -p minikube docker-env)
          docker build -t devopshint/node-app:latest .
          docker images
    - name: Apply Kubernetes Deployment
      run: kubectl apply -f k8s-node-app.yaml
    - name: Debug Pod Status
      run: kubectl get pods -A
    - name: Check Deployment Status
      run: kubectl describe deployment nodejs-app
    - name: Wait for Pod to Start
      run: sleep 30
    - name: Get Pod Logs
      run: kubectl logs -l app=nodejs-app
    - name: Test Service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url
